
version: "3.9"

services:
  backend:
    build: ./app
    container_name: em-backend   # понятное имя
    networks:
      - em-net

  nginx:
    image: nginx:1.25-alpine
    container_name: em-nginx     # понятное имя
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"                  # пробрасываем только порт 80 на хост
    depends_on:
      - backend
    networks:
      - em-net

networks:
  em-net:
    driver: bridge


